openapi: 3.0.1
info:
  title: rest-api
  description: Public REST API
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: http://rest-api.default.svc.cluster.local
paths:
  /agent/{conversation_id}:
    $ref: ./paths/agent.conversation_id.yaml
