base-service:
  name: consumer-web
  team: platform

  serviceAccount:
    create: true

  env:
    REDIS_HOST: redis
    REDIS_PORT: "6379"

  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 2
    failureThreshold: 30
    successThreshold: 1
    timeoutSeconds: 3
