compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmScopes:
  justtellme:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://us-central1-npm.pkg.dev/justtellme-platform/npm-packages/"
    npmRegistryServer: "https://us-central1-npm.pkg.dev/justtellme-platform/npm-packages/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-gcp-auth.cjs
    spec: "https://github.com/AndyClausen/yarn-plugin-gcp-auth/releases/latest/download/plugin-gcp-auth.js"
