DROP FUNCTION IF EXISTS create_address;
DROP TABLE IF EXISTS address_map;
DROP TABLE IF EXISTS address_scopes;
DROP TABLE IF EXISTS addresses;
DROP EXTENSION IF EXISTS postgis;
DROP FUNCTION IF EXISTS public.upsert_identifiers (uuid, json);
DROP TYPE IF EXISTS identifier_detail;
DROP FUNCTION IF EXISTS public.upsert_identifier (text, text, text, boolean, timestamp without time zone);
DROP TYPE IF EXISTS upserted_individual;
DROP FUNCTION IF EXISTS public.update_individual_encrypted_profile (uuid, text, text, integer, text, text, json);
DROP FUNCTION IF EXISTS public.update_individual_profile (uuid, text, text, integer, json);
DROP FUNCTION IF EXISTS json_patch (jsonb, json);
DROP TABLE IF EXISTS individual_consents;
DROP TABLE IF EXISTS consent_versions;
DROP TABLE IF EXISTS consent_types;
DROP TABLE IF EXISTS individual_relations;
DROP TYPE IF EXISTS relation_type_enum;
DROP TABLE IF EXISTS individual_addresses;
DROP TABLE IF EXISTS address_types;
DROP TABLE IF EXISTS individual_profiles;
DROP TABLE IF EXISTS profile_schemas;
DROP TABLE IF EXISTS group_identifiers;
DROP TABLE IF EXISTS individual_group_members;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS group_types;
DROP TABLE IF EXISTS individual_identifiers;
DROP TABLE IF EXISTS identifier_namespaces;
DROP TYPE IF EXISTS identifier_namespace_type_enum;
DROP TABLE IF EXISTS individual_tags;
DROP TABLE IF EXISTS individuals;
DROP TYPE IF EXISTS biological_sex_enum;
DROP ROLE IF EXISTS "identity-manager";
DROP EXTENSION IF EXISTS ltree;
DROP EXTENSION IF EXISTS plv8;
