CREATE EXTENSION IF NOT EXISTS plv8;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE EXTENSION IF NOT EXISTS ltree
WITH
  SCHEMA public;

DO $do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'identity-manager') THEN

      RAISE NOTICE 'Role "identity-manager" already exists. Skipping.';
   ELSE
      CREATE ROLE "identity-manager";
   END IF;
END
$do$;

CREATE TYPE biological_sex_enum AS ENUM('female', 'male', 'other');

-- Table Definition
CREATE TABLE individuals (
  "individual_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "biological_sex" "public"."biological_sex_enum",
  "birthdate" date,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX individuals_by_uuid ON public.individuals USING btree (individual_uuid);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individuals TO "identity-manager";

-- Table Definition
CREATE TABLE individual_tags (
  "individual_tag_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_id" int8 NOT NULL,
  "value" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "individual_tags_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id")
);

CREATE UNIQUE INDEX idx_individual_tags_uq ON public.individual_tags USING btree (individual_id, value)
WHERE
  (deleted_at IS NULL);

CREATE INDEX idx_individual_tas_by_tag ON public.individual_tags USING btree (value)
WHERE
  (deleted_at IS NULL);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_tags TO "identity-manager";

CREATE TYPE identifier_namespace_type_enum AS ENUM('email', 'phone', 'individual_name', 'uuid', 'third_party');

CREATE TABLE identifier_namespaces (
  "identifier_namespace_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identifier_namespace_type" "public"."identifier_namespace_type_enum" NOT NULL,
  "name" text NOT NULL,
  "is_unique" bool NOT NULL DEFAULT TRUE,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now())
);

GRANT
SELECT
,
  INSERT ON TABLE identifier_namespaces TO "identity-manager";

CREATE TABLE individual_identifiers (
  "individual_identifier_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_id" int8 NOT NULL,
  "identifier_namespace_id" int4 NOT NULL,
  "identifier" text NOT NULL,
  "display_identifier" text,
  "is_unique" bool DEFAULT TRUE,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "verified_at" timestamp,
  "deleted_at" timestamp,
  "released_at" timestamp,
  "updated_at" timestamp,
  CONSTRAINT "individual_identifiers_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id"),
  CONSTRAINT "individual_identifiers_identifier_namespace_id_fkey" FOREIGN KEY ("identifier_namespace_id") REFERENCES "public"."identifier_namespaces" ("identifier_namespace_id")
);

CREATE UNIQUE INDEX individual_identifiers_ukey_notnull ON public.individual_identifiers USING btree (identifier, identifier_namespace_id)
WHERE
  (
    (released_at IS NULL)
    AND (is_unique IS TRUE)
  );

CREATE INDEX individual_identifiers_by_individual ON public.individual_identifiers USING btree (individual_id, identifier_namespace_id);

CREATE INDEX individual_identifiers_by_is_non_unique ON public.individual_identifiers USING btree (identifier_namespace_id, identifier)
WHERE
  (
    (released_at IS NULL)
    AND (is_unique IS FALSE)
  );

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_identifiers TO "identity-manager";

CREATE TABLE group_types (
  group_type_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp DEFAULT timezone ('utc'::text, now()) NOT NULL
);

GRANT
SELECT
  ON TABLE group_types TO "identity-manager";

INSERT INTO
  group_types (name)
VALUES
  ('default');

CREATE TABLE groups (
  "group_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "group_type_id" int NOT NULL REFERENCES group_types (group_type_id),
  "name" ltree NOT NULL,
  "display_name" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX group_by_name ON groups USING btree (name);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE groups TO "identity-manager";

CREATE TABLE individual_group_members (
  "individual_group_member_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int8 NOT NULL,
  "individual_id" int8 NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "created_by_individual_id" int8,
  "deleted_by_individual_id" int8,
  "begins_at" timestamp,
  "ends_at" timestamp,
  CONSTRAINT "individual_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("group_id"),
  CONSTRAINT "individual_group_members_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id")
);

CREATE INDEX individual_group_by_individual ON public.individual_group_members USING btree (individual_id, group_id);

CREATE INDEX individual_group_by_group ON public.individual_group_members USING btree (group_id, individual_id);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_group_members TO "identity-manager";

-- Table Definition
CREATE TABLE group_identifiers (
  "group_identifier_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int8 NOT NULL,
  "identifier_namespace_id" int4 NOT NULL,
  "is_unique" bool DEFAULT TRUE,
  "identifier" text NOT NULL,
  "display_identifier" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "released_at" timestamp,
  "updated_at" timestamp,
  CONSTRAINT "group_identifiers_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."groups" ("group_id"),
  CONSTRAINT "group_identifiers_identifier_namespace_id_fkey" FOREIGN KEY ("identifier_namespace_id") REFERENCES "public"."identifier_namespaces" ("identifier_namespace_id")
);

CREATE UNIQUE INDEX grouop_identifiers_ukey_notnull ON public.group_identifiers USING btree (identifier, identifier_namespace_id)
WHERE
  (
    (released_at IS NULL)
    AND (is_unique IS TRUE)
  );

CREATE INDEX group_identifiers_by_individual ON public.group_identifiers USING btree (group_id, identifier_namespace_id);

CREATE INDEX group_identifiers_by_is_non_unique ON public.group_identifiers USING btree (identifier_namespace_id, identifier)
WHERE
  (
    (released_at IS NULL)
    AND (is_unique IS FALSE)
  );

GRANT
SELECT
,
  INSERT ON TABLE group_identifiers TO "identity-manager";

-- Table Definition
CREATE TABLE profile_schemas (
  "profile_schema_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "is_encrypted" bool NOT NULL DEFAULT FALSE,
  "audited" bool NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX profile_schemas_name_key ON public.profile_schemas USING btree (name);

GRANT
SELECT
,
  INSERT ON TABLE profile_schemas TO "identity-manager";

-- Table Definition
CREATE TABLE individual_profiles (
  "individual_profile_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_id" int8 NOT NULL,
  "profile_schema_id" int4 NOT NULL,
  "instance_name" text,
  "profile" jsonb NOT NULL,
  "version" int4 NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "encrypted_profile" bytea,
  CONSTRAINT "individual_profiles_profile_schema_id_fkey" FOREIGN KEY ("profile_schema_id") REFERENCES "public"."profile_schemas" ("profile_schema_id"),
  CONSTRAINT "individual_profiles_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id")
);

CREATE UNIQUE INDEX individual_profiles_ukey_notnull_nd ON public.individual_profiles USING btree (individual_id, profile_schema_id, instance_name)
WHERE
  (
    (instance_name IS NOT NULL)
    AND (deleted_at IS NULL)
  );

CREATE UNIQUE INDEX individual_profiles_ukey_null_nd ON public.individual_profiles USING btree (individual_id, profile_schema_id)
WHERE
  (
    (instance_name IS NULL)
    AND (deleted_at IS NULL)
  );

CREATE INDEX individual_profiles_by_individual ON public.individual_profiles USING btree (individual_id, profile_schema_id)
WHERE
  (deleted_at IS NULL);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_profiles TO "identity-manager";

-- Table Definition
CREATE TABLE address_types (
  "address_type_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now())
);

CREATE UNIQUE INDEX address_type_pkey ON public.address_types USING btree (address_type_id);

CREATE UNIQUE INDEX address_types_unique_name ON public.address_types USING btree (name);

GRANT
SELECT
,
  INSERT ON TABLE address_types TO "identity-manager";

CREATE TABLE
  addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SHA1 hash of normalized address components for deduplication
    address_key TEXT NOT NULL,
    line_1 TEXT,
    line_2 TEXT,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country CHAR(2) NOT NULL,
    geolocation GEOGRAPHY (POINT, 4326),
    detail jsonb,
    superseded_by_address_id BIGINT REFERENCES addresses (address_id),
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE INDEX idx_geography_location ON addresses USING GIST (geolocation);

CREATE UNIQUE INDEX idx_addresses_by_key ON addresses (address_key);

-- Table Definition
CREATE TABLE individual_addresses (
  "individual_address_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_id" int8 NOT NULL,
  "address_id" int8 NOT NULL,
  "address_type_id" int4,
  -- Sometimes you may want an individual to have multiple addresses of a given type.
  -- The instance_name allows you to do that.
  "instance_name" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "individual_addresses_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id"),
  CONSTRAINT "individual_addresses_address_type_id_fkey" FOREIGN KEY ("address_type_id") REFERENCES "public"."address_types" ("address_type_id"),
  CONSTRAINT "individual_addresses_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."addresses" ("address_id")
);

-- One row per (individual_id, address_type_id) when instance_name is null
CREATE UNIQUE INDEX address_by_individual_null_instance ON public.individual_addresses USING btree (individual_id, address_type_id)
WHERE
  (
    deleted_at IS NULL
    AND instance_name IS NULL
  );

-- One row per (individual_id, address_type_id, instance_name) when instance_name is not null
CREATE UNIQUE INDEX address_by_individual_with_instance ON public.individual_addresses USING btree (individual_id, address_type_id, instance_name)
WHERE
  (
    deleted_at IS NULL
    AND instance_name IS NOT NULL
  );

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_addresses TO "identity-manager";

CREATE TYPE relation_type_enum AS ENUM(
  'is_partner_of',
  'is_guardian_of',
  'is_child_of',
  'is_sibling_of',
  'booked_as_friend_of',
  'booked_for',
  'played_with',
  'studied_with'
);

-- Table Definition
CREATE TABLE individual_relations (
  "individual_relation_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_individual_id" int8 NOT NULL,
  "object_individual_id" int8 NOT NULL,
  "relation_type" "public"."relation_type_enum" NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "individual_relations_subject_individual_id_fkey" FOREIGN KEY ("subject_individual_id") REFERENCES "public"."individuals" ("individual_id"),
  CONSTRAINT "individual_relations_object_individual_id_fkey" FOREIGN KEY ("object_individual_id") REFERENCES "public"."individuals" ("individual_id")
);

CREATE UNIQUE INDEX individual_relation_forward ON public.individual_relations USING btree (subject_individual_id, relation_type, object_individual_id)
WHERE
  (deleted_at IS NULL);

CREATE INDEX individual_relation_backward ON public.individual_relations USING btree (object_individual_id, relation_type, subject_individual_id)
WHERE
  (deleted_at IS NULL);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_relations TO "identity-manager";

-- Table Definition
CREATE TABLE consent_types (
  "consent_type_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamp
);

GRANT
SELECT
,
  INSERT ON TABLE consent_types TO "identity-manager";

-- Table Definition
CREATE TABLE consent_versions (
  "consent_version_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consent_type_id" int4 NOT NULL,
  "name" text NOT NULL,
  "url" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  CONSTRAINT "consent_versions_consent_type_id_fkey" FOREIGN KEY ("consent_type_id") REFERENCES "public"."consent_types" ("consent_type_id")
);

GRANT
SELECT
,
  INSERT ON TABLE consent_versions TO "identity-manager";

-- Table Definition
CREATE TABLE individual_consents (
  "individual_consent_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "individual_id" int8 NOT NULL,
  "consent_version_id" int4 NOT NULL,
  "consent_scope" text,
  "is_granted" bool NOT NULL,
  "evidence" jsonb,
  "detail" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT timezone ('utc'::text, now()),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "individual_consents_individual_id_fkey" FOREIGN KEY ("individual_id") REFERENCES "public"."individuals" ("individual_id"),
  CONSTRAINT "individual_consents_consent_version_id_fkey" FOREIGN KEY ("consent_version_id") REFERENCES "public"."consent_versions" ("consent_version_id")
);

-- Indices
CREATE INDEX idx_individual_consents ON public.individual_consents USING btree (individual_id, consent_scope, consent_version_id);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE individual_consents TO "identity-manager";

CREATE OR REPLACE FUNCTION json_patch (input_json jsonb, patch_json json) RETURNS json LANGUAGE plv8 IMMUTABLE STRICT AS $_$
const module = { exports: {} };

{{{jsonpatch.js}}}

  /* If patch test fails, return the original to ensure upsert functionality can work  */
  const original = JSON.stringify(input_json || {});
  try {
    return module.exports.jsonpatch.apply(input_json || {}, patch_json);
  } catch (error) {
    if (error instanceof module.exports.PatchTestFailed) {
      return JSON.parse(original);
    }
    throw error;
  }
$_$;

CREATE OR REPLACE FUNCTION public.update_individual_profile (
  _individual_uuid uuid,
  _schema_name text,
  _instance_name text,
  _version integer,
  _patch_json json
) RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
  _individual_id bigint;
  _profile_schema_id int;
  _final_profile json;
  _enc boolean;
BEGIN
  SELECT individual_id INTO _individual_id FROM individuals WHERE individual_uuid = _individual_uuid;

  IF _individual_id IS NULL THEN
    RAISE EXCEPTION '[APP:NOTFOUND] No match individual found' USING ERRCODE = '22000';
  END IF;

  SELECT profile_schema_id, is_encrypted INTO _profile_schema_id, _enc FROM profile_schemas WHERE name = _schema_name;

  IF _profile_schema_id IS NULL THEN
    RAISE EXCEPTION '[IDENTITY:CONFIG] No profile schema found named %', _schema_name USING ERRCODE = '22000';
  END IF;
  IF _enc THEN
    RAISE EXCEPTION '[IDENTITY:CONFIG] Profile schema % is encrypted', _schema_name USING ERRCODE = '22000';
  END IF;

  IF _instance_name IS NOT NULL THEN
    INSERT INTO
  	individual_profiles as existing_profile
  	(individual_id, profile_schema_id, instance_name, version, profile)
    VALUES
  	(_individual_id, _profile_schema_id, _instance_name, _version, json_patch('{}', _patch_json))
    ON CONFLICT (individual_id, profile_schema_id, instance_name) WHERE instance_name IS NOT NULL AND deleted_at IS NULL
    DO UPDATE SET
  	profile = (json_patch(existing_profile.profile, _patch_json)),
    version = _version,
    updated_at = NOW()
    WHERE
  	existing_profile.individual_id = _individual_id
    AND existing_profile.instance_name = _instance_name
    AND existing_profile.profile_schema_id = _profile_schema_id
    RETURNING profile INTO _final_profile;
  ELSE
    INSERT INTO
  	individual_profiles as existing_profile
  	(individual_id, profile_schema_id, version, profile)
    VALUES
  	(_individual_id, _profile_schema_id, _version, json_patch('{}', _patch_json))
    ON CONFLICT (individual_id, profile_schema_id) WHERE instance_name IS NULL AND deleted_at IS NULL
    DO UPDATE SET
  	profile = (json_patch(existing_profile.profile, _patch_json)),
    version = _version,
    updated_at = NOW()
    WHERE
  	existing_profile.individual_id = _individual_id
    AND existing_profile.instance_name IS NULL
    AND existing_profile.profile_schema_id = _profile_schema_id
    RETURNING profile INTO _final_profile;
  END IF;

  RETURN _final_profile;
END
$function$;

CREATE OR REPLACE FUNCTION public.update_individual_encrypted_profile (
  _individual_uuid uuid,
  _schema_name text,
  _instance_name text,
  _version integer,
  key_id text,
  hex_key text,
  _patch_json json
) RETURNS text LANGUAGE plpgsql AS $function$
DECLARE
  _individual_id bigint;
  _profile_schema_id int;
  _final_profile bytea;
  _key bytea;
  _iv bytea;
  _enc boolean;
BEGIN
  SELECT individual_id INTO _individual_id FROM individuals WHERE individual_uuid = _individual_uuid;
  _key := decode(hex_key, 'hex');
  _iv := gen_random_bytes(16);

  IF _individual_id IS NULL THEN
    RAISE EXCEPTION '[APP:NOTFOUND] No match individual found' USING ERRCODE = '22000';
  END IF;

  SELECT profile_schema_id, is_encrypted INTO _profile_schema_id, _enc FROM profile_schemas WHERE name = _schema_name;

  IF _profile_schema_id IS NULL THEN
    RAISE EXCEPTION '[APP:CONFIG] No profile schema found named %', _schema_name USING ERRCODE = '22000';
  END IF;
  IF _enc = false THEN
    RAISE EXCEPTION '[APP:CONFIG] Profile schema % is not encrypted', _schema_name USING ERRCODE = '22000';
  END IF;

  IF _instance_name IS NOT NULL THEN
    INSERT INTO
    	individual_profiles as existing_profile
    	(individual_id, profile_schema_id, instance_name, version, profile, encrypted_profile)
    VALUES
  	  (_individual_id, _profile_schema_id, _instance_name, _version,
        to_jsonb(key_id),
        encrypt_json(json_patch('{}', _patch_json), _key, _iv)
      )
    ON CONFLICT (individual_id, profile_schema_id, instance_name) WHERE instance_name IS NOT NULL AND deleted_at IS NULL
    DO UPDATE SET
  	encrypted_profile = (
      encrypt_json(
        json_patch(
          decrypt_json(existing_profile.encrypted_profile, _key),
          _patch_json
        ),
        _key,
        _iv
      )
    ),
    version = _version,
    updated_at = NOW()
    WHERE
  	existing_profile.individual_id = _individual_id
    AND existing_profile.instance_name = _instance_name
    AND existing_profile.profile_schema_id = _profile_schema_id
    RETURNING encrypted_profile INTO _final_profile;
  ELSE
    INSERT INTO
    	individual_profiles as existing_profile
    	(individual_id, profile_schema_id, version, profile, encrypted_profile)
    VALUES
  	  (_individual_id, _profile_schema_id, _version,
        to_jsonb(key_id),
        encrypt_json(json_patch('{}', _patch_json), _key, _iv)
      )
    ON CONFLICT (individual_id, profile_schema_id) WHERE instance_name IS NULL AND deleted_at IS NULL
    DO UPDATE SET
  	encrypted_profile = (
      encrypt_json(
        json_patch(
          decrypt_json(existing_profile.encrypted_profile, _key),
          _patch_json
        ),
        _key,
        _iv
      )
    ),
    version = _version,
    updated_at = NOW()
    WHERE
  	existing_profile.individual_id = _individual_id
    AND existing_profile.instance_name IS NULL
    AND existing_profile.profile_schema_id = _profile_schema_id
    RETURNING encrypted_profile INTO _final_profile;
  END IF;

  RETURN encode(_final_profile, 'hex');
END
$function$;

CREATE TYPE upserted_individual AS (
  inserted BOOLEAN,
  individual_id INTEGER,
  individual_uuid UUID,
  error text,
  created_at TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.upsert_identifier (
  _namespace_name text,
  _identifier text,
  _display_identifier text,
  _is_unique boolean,
  _released_at timestamp without time zone DEFAULT NULL::timestamp without time zone
) RETURNS upserted_individual LANGUAGE plpgsql AS $function$

DECLARE
  _namespace_id int;
  _indvidual_id int;
  _inserted boolean;
  _individual upserted_individual;

BEGIN
  SELECT
    identifier_namespace_id, type
  INTO
    _namespace_id
  FROM
    identifier_namespaces
  WHERE
    name = _namespace_name;

  IF _namespace_id IS NULL THEN
    RAISE EXCEPTION '[APP:CONFIG] No namespace found matching %', _namespace_name USING ERRCODE = '22000';
  END IF;

  SELECT
    individual_id, false
  INTO
    _indvidual_id, _inserted
  FROM
    individual_identifiers
  WHERE
    identifier_namespace_id = _namespace_id
    AND _is_unique = true
    AND identifier = _identifier
    AND released_at IS NULL;

  IF _indvidual_id IS NULL THEN
    _inserted := true;
    INSERT INTO individuals DEFAULT VALUES RETURNING individual_id INTO _indvidual_id;
    INSERT INTO individual_identifiers
      (individual_id, is_unique, identifier, display_identifier, identifier_namespace_id, released_at)
    VALUES
      (_indvidual_id, _is_unique, _identifier, _display_identifier, _namespace_id, _released_at);
  END IF;

  SELECT
    individual_id, individual_uuid, created_at, _inserted, _identifier
  INTO
    _individual.individual_id, _individual.individual_uuid,
    _individual.created_at, _individual.inserted, _individual.identifier
  FROM
    individuals
  WHERE
    individual_id = _indvidual_id;

  RETURN _individual;
END
$function$;

CREATE TYPE identifier_detail AS (
  identifier_namespace_id INTEGER,
  identifier text,
  display_identifier text,
  is_unique boolean
);

CREATE OR REPLACE FUNCTION public.upsert_identifiers (_individual_uuid uuid, _jsonidentifiers json) RETURNS upserted_individual LANGUAGE plpgsql AS $function$
DECLARE
	_individual_id int;
  _min_id int;
  _max_id int;
  _inserted boolean;
	_individual upserted_individual;
  _identifiers identifier_detail[];
BEGIN
  WITH cte AS (
    SELECT x
    FROM json_populate_recordset(NULL::identifier_detail, _jsonIdentifiers) AS x
  )
  SELECT array_agg(x) INTO _identifiers FROM cte;

  IF _individual_uuid IS NOT NULL THEN
    SELECT
      individual_id
    INTO
      _individual_id
    FROM
      individuals
    WHERE
      individual_uuid = _individual_uuid;
  END IF;

  WITH passed AS (
    SELECT identifier_namespace_id, identifier
    FROM unnest(_identifiers) p
    WHERE p.is_unique = true
  )
  SELECT
    MIN(individual_id),
    MAX(individual_id)
  INTO
    _min_id, _max_id
  FROM
    individual_identifiers a
    INNER JOIN passed p ON
      a.identifier = p.identifier
      AND a.identifier_namespace_id = p.identifier_namespace_id
      AND a.released_at IS NULL
      AND a.is_unique IS TRUE;

  IF (_min_id IS NOT NULL AND _min_id <> _max_id)
    OR (_individual_uuid IS NOT NULL AND _min_id IS NOT NULL AND (_individual_id IS NULL OR _individual_id <> _min_id)) THEN
    SELECT individual_id, individual_uuid, 'CONFLICT'
    INTO _individual.individual_id, _individual.individual_uuid, _individual.error
    FROM individuals
    WHERE individual_id = _min_id;
    RETURN _individual;
  END IF;

  IF _min_id IS NOT NULL THEN
    _individual_id := _min_id;
  END IF;

  IF _individual_id IS NULL THEN
    _inserted := true;
    IF _individual_uuid IS NOT NULL THEN
      INSERT INTO individuals (individual_uuid) VALUES (_individual_uuid) RETURNING individual_id INTO _individual_id;
    ELSE
      INSERT INTO individuals DEFAULT VALUES RETURNING individual_id INTO _individual_id;
    END IF;
	END IF;

  WITH passed AS (
    SELECT p.identifier, p.display_identifier, p.is_unique, p.identifier_namespace_id
    FROM unnest(_identifiers) p
  )
  INSERT INTO
    individual_identifiers (individual_id, is_unique, identifier, display_identifier, identifier_namespace_id)
  SELECT
    _individual_id,
    is_unique,
    identifier,
    display_identifier,
    identifier_namespace_id
  FROM passed p
  -- TODO insert where not exists is not atomic I don't think, so this could use a fixup
  WHERE NOT EXISTS
    (SELECT 1 FROM individual_identifiers i2 WHERE
      p.identifier_namespace_id = i2.identifier_namespace_id AND
      i2.identifier = p.identifier AND i2.released_at IS NULL AND
      i2.individual_id = _individual_id);

  SELECT
		individual_id, individual_uuid, created_at, _inserted
	INTO
		_individual.individual_id, _individual.individual_uuid, _individual.created_at, _individual.inserted
	FROM
		individuals
	WHERE
		individual_id = _individual_id;

	RETURN _individual;
END
$function$;

-- Namespace seed data (consolidated from namespaces migration)
INSERT INTO identifier_namespaces (name, identifier_namespace_type, is_unique) VALUES
  ('consumer-email', 'email', true),
  ('phone', 'phone', true),
  ('consumer-phone', 'phone', true),
  ('individual-name', 'individual_name', false),
  ('consumer-uuid', 'uuid', true),
  ('stripe-customer', 'third_party', true),
  ('stytch-consumer', 'third_party', true),
  ('consumer-apple', 'third_party', true),
  ('consumer-google', 'third_party', true),
  ('stytch-admin', 'third_party', true),
  ('stytch-provider', 'third_party', true);

-- Address schema (consolidated from address-schema migration)
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE
  address_scopes (
    address_scope_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_scope_name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE TABLE
  address_map (
    address_map_uuid UUID DEFAULT gen_random_uuid () NOT NULL PRIMARY KEY,
    address_id BIGINT NOT NULL REFERENCES addresses (address_id),
    address_scope_id INT NOT NULL REFERENCES address_scopes (address_scope_id),
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE UNIQUE INDEX idx_address_map_by_address_id ON address_map (address_id, address_scope_id);

GRANT SELECT ON address_scopes TO "identity-manager";
GRANT INSERT, UPDATE, SELECT ON addresses TO "identity-manager";
GRANT INSERT, UPDATE, SELECT ON address_map TO "identity-manager";

INSERT INTO address_scopes (address_scope_name) VALUES ('consumer');
INSERT INTO address_scopes (address_scope_name) VALUES ('provider');
INSERT INTO address_scopes (address_scope_name) VALUES ('lab');
INSERT INTO address_scopes (address_scope_name) VALUES ('pharmacy');

CREATE FUNCTION create_address (
  _address_key TEXT,
  _address_scope_name TEXT,
  _line_1 TEXT,
  _line_2 TEXT,
  _city TEXT,
  _state TEXT,
  _postal_code TEXT,
  _country CHARACTER,
  _geolocation GEOGRAPHY (POINT, 4326) = NULL,
  _detail jsonb = NULL
) RETURNS UUID LANGUAGE plpgsql AS $$
  DECLARE
    _address_id bigint;
    _address_scope_id int;
    _address_map_uuid uuid;
  BEGIN
    SELECT address_scope_id INTO _address_scope_id
    FROM address_scopes
    WHERE address_scope_name = _address_scope_name;

    IF _address_scope_id IS NULL THEN
      RAISE EXCEPTION 'Address scope % does not exist', _address_scope_name;
    END IF;

    SELECT COALESCE(superseded_by_address_id, address_id) INTO _address_id
    FROM addresses
    WHERE address_key = _address_key;

    IF _address_id IS NULL THEN
      INSERT INTO addresses
        (address_key, line_1, line_2, city, state, postal_code, country, geolocation, detail)
      VALUES
        (_address_key, _line_1, _line_2, _city, _state, _postal_code, _country, _geolocation, _detail)
      ON CONFLICT (address_key) DO UPDATE SET
        geolocation = COALESCE(EXCLUDED.geolocation, addresses.geolocation),
        detail = COALESCE(EXCLUDED.detail, addresses.detail)
      RETURNING address_id INTO _address_id;
    END IF;

    INSERT INTO address_map
      (address_id, address_scope_id)
    VALUES
      (_address_id, _address_scope_id)
    ON CONFLICT
      (address_id, address_scope_id)
    DO UPDATE SET address_id = EXCLUDED.address_id
    RETURNING address_map_uuid INTO _address_map_uuid;

    RETURN _address_map_uuid;
  END;
  $$;
