CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE
  addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SHA1 hash of normalized address components for deduplication
    address_key TEXT NOT NULL,
    line_1 TEXT,
    line_2 TEXT,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    country CHAR(2) NOT NULL,
    geolocation GEOGRAPHY (POINT, 4326),
    detail jsonb,
    superseded_by_address_id BIGINT REFERENCES addresses (address_id),
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE INDEX idx_geography_location ON addresses USING GIST (geolocation);

CREATE UNIQUE INDEX idx_addresses_by_key ON addresses (address_key);

CREATE TABLE
  address_scopes (
    address_scope_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_scope_name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE TABLE
  address_map (
    address_map_uuid UUID DEFAULT gen_random_uuid () NOT NULL PRIMARY KEY,
    address_id BIGINT NOT NULL REFERENCES addresses (address_id),
    address_scope_id INT NOT NULL REFERENCES address_scopes (address_scope_id),
    created_at TIMESTAMP DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP
  );

CREATE UNIQUE INDEX idx_address_map_by_address_id ON address_map (address_id, address_scope_id);

GRANT SELECT ON address_scopes TO "identity-manager";

GRANT INSERT, UPDATE, SELECT ON addresses TO "identity-manager";

GRANT INSERT, UPDATE, SELECT ON address_map TO "identity-manager";

INSERT INTO address_scopes (address_scope_name) VALUES ('consumer');
INSERT INTO address_scopes (address_scope_name) VALUES ('provider');
INSERT INTO address_scopes (address_scope_name) VALUES ('lab');
INSERT INTO address_scopes (address_scope_name) VALUES ('pharmacy');

CREATE FUNCTION create_address (
  _address_key TEXT,
  _address_scope_name TEXT,
  _line_1 TEXT,
  _line_2 TEXT,
  _city TEXT,
  _state TEXT,
  _postal_code TEXT,
  _country CHARACTER,
  _geolocation GEOGRAPHY (POINT, 4326) = NULL,
  _detail jsonb = NULL
) RETURNS UUID LANGUAGE plpgsql AS $$
  DECLARE
    _address_id bigint;
    _address_scope_id int;
    _address_map_uuid uuid;
  BEGIN
    SELECT address_scope_id INTO _address_scope_id
    FROM address_scopes
    WHERE address_scope_name = _address_scope_name;

    IF _address_scope_id IS NULL THEN
      RAISE EXCEPTION 'Address scope % does not exist', _address_scope_name;
    END IF;

    SELECT COALESCE(superseded_by_address_id, address_id) INTO _address_id
    FROM addresses
    WHERE address_key = _address_key;

    IF _address_id IS NULL THEN
      INSERT INTO addresses
        (address_key, line_1, line_2, city, state, postal_code, country, geolocation, detail)
      VALUES
        (_address_key, _line_1, _line_2, _city, _state, _postal_code, _country, _geolocation, _detail)
      ON CONFLICT (address_key) DO UPDATE SET
        geolocation = COALESCE(EXCLUDED.geolocation, addresses.geolocation),
        detail = COALESCE(EXCLUDED.detail, addresses.detail)
      RETURNING address_id INTO _address_id;
    END IF;

    INSERT INTO address_map
      (address_id, address_scope_id)
    VALUES
      (_address_id, _address_scope_id)
    ON CONFLICT
      (address_id, address_scope_id)
    DO UPDATE SET address_id = EXCLUDED.address_id
    RETURNING address_map_uuid INTO _address_map_uuid;

    RETURN _address_map_uuid;
  END;
  $$;
