CREATE TABLE group_profiles (
  "group_profile_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int8 NOT NULL REFERENCES public.groups (group_id),
  "profile_schema_id" int4 NOT NULL REFERENCES public.profile_schemas (profile_schema_id),
  "instance_name" text,
  "profile" jsonb NOT NULL,
  "version" int4 NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "updated_at" timestamp,
  "deleted_at" timestamp,
  "encrypted_profile" bytea
);

CREATE UNIQUE INDEX group_profiles_instance_unique
  ON group_profiles (group_id, profile_schema_id, instance_name)
  WHERE instance_name IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX group_profiles_default_unique
  ON group_profiles (group_id, profile_schema_id)
  WHERE instance_name IS NULL AND deleted_at IS NULL;
CREATE INDEX group_profiles_by_group
  ON group_profiles (group_id)
  WHERE deleted_at IS NULL;

GRANT SELECT, INSERT, UPDATE ON TABLE group_profiles TO "identity-manager";

CREATE OR REPLACE FUNCTION public.update_group_profile (
  _group_uuid uuid,
  _schema_name text,
  _instance_name text,
  _version integer,
  _patch_json json
) RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
  _group_id bigint;
  _profile_schema_id int;
  _final_profile json;
  _encrypted boolean;
BEGIN
  SELECT group_id INTO _group_id FROM groups WHERE group_uuid = _group_uuid;
  IF _group_id IS NULL THEN
    RAISE EXCEPTION '[APP:NOTFOUND] No matching group found' USING ERRCODE = '22000';
  END IF;

  SELECT profile_schema_id, is_encrypted
    INTO _profile_schema_id, _encrypted
    FROM profile_schemas WHERE name = _schema_name;
  IF _profile_schema_id IS NULL THEN
    RAISE EXCEPTION '[IDENTITY:CONFIG] No profile schema found named %', _schema_name USING ERRCODE = '22000';
  END IF;
  IF _encrypted THEN
    RAISE EXCEPTION '[IDENTITY:CONFIG] Profile schema % is encrypted', _schema_name USING ERRCODE = '22000';
  END IF;

  IF _instance_name IS NULL THEN
    INSERT INTO group_profiles AS existing_profile
      (group_id, profile_schema_id, version, profile)
    VALUES
      (_group_id, _profile_schema_id, _version, json_patch('{}', _patch_json))
    ON CONFLICT (group_id, profile_schema_id)
      WHERE instance_name IS NULL AND deleted_at IS NULL
    DO UPDATE SET
      profile = json_patch(existing_profile.profile, _patch_json),
      version = _version,
      updated_at = NOW()
    RETURNING profile INTO _final_profile;
  ELSE
    INSERT INTO group_profiles AS existing_profile
      (group_id, profile_schema_id, instance_name, version, profile)
    VALUES
      (_group_id, _profile_schema_id, _instance_name, _version, json_patch('{}', _patch_json))
    ON CONFLICT (group_id, profile_schema_id, instance_name)
      WHERE instance_name IS NOT NULL AND deleted_at IS NULL
    DO UPDATE SET
      profile = json_patch(existing_profile.profile, _patch_json),
      version = _version,
      updated_at = NOW()
    RETURNING profile INTO _final_profile;
  END IF;

  RETURN _final_profile;
END
$function$;

CREATE OR REPLACE FUNCTION public.update_group_encrypted_profile (
  _group_uuid uuid,
  _schema_name text,
  _instance_name text,
  _version integer,
  key_id text,
  hex_key text,
  _patch_json json
) RETURNS text LANGUAGE plpgsql AS $function$
DECLARE
  _group_id bigint;
  _profile_schema_id int;
  _final_profile bytea;
  _key bytea;
  _iv bytea;
  _encrypted boolean;
BEGIN
  SELECT group_id INTO _group_id FROM groups WHERE group_uuid = _group_uuid;
  _key := decode(hex_key, 'hex');
  _iv := gen_random_bytes(16);
  IF _group_id IS NULL THEN
    RAISE EXCEPTION '[APP:NOTFOUND] No matching group found' USING ERRCODE = '22000';
  END IF;

  SELECT profile_schema_id, is_encrypted
    INTO _profile_schema_id, _encrypted
    FROM profile_schemas WHERE name = _schema_name;
  IF _profile_schema_id IS NULL THEN
    RAISE EXCEPTION '[APP:CONFIG] No profile schema found named %', _schema_name USING ERRCODE = '22000';
  END IF;
  IF _encrypted = false THEN
    RAISE EXCEPTION '[APP:CONFIG] Profile schema % is not encrypted', _schema_name USING ERRCODE = '22000';
  END IF;

  IF _instance_name IS NULL THEN
    INSERT INTO group_profiles AS existing_profile
      (group_id, profile_schema_id, version, profile, encrypted_profile)
    VALUES (_group_id, _profile_schema_id, _version, to_jsonb(key_id),
      encrypt_json(json_patch('{}', _patch_json), _key, _iv))
    ON CONFLICT (group_id, profile_schema_id)
      WHERE instance_name IS NULL AND deleted_at IS NULL
    DO UPDATE SET
      encrypted_profile = encrypt_json(
        json_patch(decrypt_json(existing_profile.encrypted_profile, _key), _patch_json),
        _key, _iv),
      version = _version,
      updated_at = NOW()
    RETURNING encrypted_profile INTO _final_profile;
  ELSE
    INSERT INTO group_profiles AS existing_profile
      (group_id, profile_schema_id, instance_name, version, profile, encrypted_profile)
    VALUES (_group_id, _profile_schema_id, _instance_name, _version, to_jsonb(key_id),
      encrypt_json(json_patch('{}', _patch_json), _key, _iv))
    ON CONFLICT (group_id, profile_schema_id, instance_name)
      WHERE instance_name IS NOT NULL AND deleted_at IS NULL
    DO UPDATE SET
      encrypted_profile = encrypt_json(
        json_patch(decrypt_json(existing_profile.encrypted_profile, _key), _patch_json),
        _key, _iv),
      version = _version,
      updated_at = NOW()
    RETURNING encrypted_profile INTO _final_profile;
  END IF;

  RETURN encode(_final_profile, 'hex');
END
$function$;

CREATE TABLE group_addresses (
  "group_address_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int8 NOT NULL REFERENCES public.groups (group_id),
  "address_id" int8 NOT NULL REFERENCES public.addresses (address_id),
  "address_type_id" int4 NOT NULL REFERENCES public.address_types (address_type_id),
  "instance_name" text,
  "created_at" timestamp NOT NULL DEFAULT timezone ('utc'::text, now()),
  "deleted_at" timestamp,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX group_address_null_instance_unique
  ON group_addresses (group_id, address_type_id)
  WHERE deleted_at IS NULL AND instance_name IS NULL;
CREATE UNIQUE INDEX group_address_with_instance_unique
  ON group_addresses (group_id, address_type_id, instance_name)
  WHERE deleted_at IS NULL AND instance_name IS NOT NULL;
CREATE INDEX group_addresses_by_group
  ON group_addresses (group_id, address_type_id)
  WHERE deleted_at IS NULL;

GRANT SELECT, INSERT, UPDATE ON TABLE group_addresses TO "identity-manager";

CREATE TABLE group_consents (
  "group_consent_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" int8 NOT NULL REFERENCES public.groups (group_id),
  "actor_individual_id" int8 NOT NULL REFERENCES public.individuals (individual_id),
  "consent_version_id" int4 NOT NULL REFERENCES public.consent_versions (consent_version_id),
  "consent_scope" text,
  "is_granted" bool NOT NULL,
  "evidence" jsonb,
  "detail" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT timezone ('utc'::text, now()),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX group_consents_by_group
  ON group_consents (group_id, consent_scope, consent_version_id, created_at DESC);
CREATE INDEX group_consents_by_actor
  ON group_consents (actor_individual_id);

GRANT SELECT, INSERT, UPDATE ON TABLE group_consents TO "identity-manager";
