DO $do$
BEGIN IF EXISTS (
        SELECT
        FROM pg_catalog.pg_roles
        WHERE rolname = 'task-manager'
    ) THEN RAISE NOTICE 'Role "task-manager" already exists. Skipping.';

ELSE CREATE ROLE "task-manager";

END IF;

END $do$;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "task-manager";

CREATE TABLE task_types (
  task_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  default_priority smallint,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE task_types TO "task-manager";

CREATE TRIGGER task_types BEFORE
UPDATE ON task_types FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TYPE task_status_enum AS ENUM('todo', 'in-progress', 'waiting', 'blocked', 'done', 'skipped');

CREATE TYPE entity_type_enum AS ENUM('user', 'agent', 'service', 'system');

CREATE TABLE tasks (
  task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  task_type_id bigint NOT NULL REFERENCES task_types (task_type_id),
  idempotency_key text,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE tasks TO "task-manager";

-- Indexes on tasks
CREATE UNIQUE INDEX idx_tasks_by_uuid ON tasks (task_uuid);

CREATE INDEX idx_tasks_by_type ON tasks (task_type_id, created_at);

CREATE INDEX idx_tasks_by_created_at ON tasks (created_at, task_id)
WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX idx_tasks_idempotency_key ON tasks (task_type_id, idempotency_key)
WHERE
  idempotency_key IS NOT NULL
  AND deleted_at IS NULL;

CREATE INDEX idx_tasks_by_idempotency_key ON tasks (idempotency_key)
WHERE
  idempotency_key IS NOT NULL
  AND deleted_at IS NULL;

CREATE TRIGGER tasks BEFORE
UPDATE ON tasks FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE task_context (
  task_id bigint PRIMARY KEY REFERENCES tasks (task_id),
  title text,
  summary text,
  submitter_type entity_type_enum,
  submitter_uuid uuid,
  subject_type entity_type_enum,
  subject_uuid uuid,
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE task_context TO "task-manager";

CREATE INDEX idx_task_context_by_subject ON task_context (subject_type, subject_uuid)
WHERE deleted_at IS NULL;

CREATE INDEX idx_task_context_by_submitter ON task_context (submitter_type, submitter_uuid)
WHERE deleted_at IS NULL;

CREATE TRIGGER task_context BEFORE
UPDATE ON task_context FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE task_tracking (
  task_id bigint PRIMARY KEY REFERENCES tasks (task_id),
  status task_status_enum NOT NULL DEFAULT 'todo',
  priority smallint NOT NULL DEFAULT 0,
  due_at timestamptz(3),
  closed_at timestamptz(3),
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE task_tracking TO "task-manager";

CREATE INDEX idx_task_tracking_by_status ON task_tracking (status, created_at)
WHERE deleted_at IS NULL;

CREATE INDEX idx_task_tracking_by_due_at ON task_tracking (due_at)
WHERE
  deleted_at IS NULL
  AND due_at IS NOT NULL;

CREATE TRIGGER task_tracking BEFORE
UPDATE ON task_tracking FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE step_types (
  step_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  default_priority smallint,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE step_types TO "task-manager";

CREATE TRIGGER step_types BEFORE
UPDATE ON step_types FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE task_steps (
  task_step_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_step_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id bigint NOT NULL REFERENCES tasks (task_id),
  step_type_id bigint NOT NULL REFERENCES step_types (step_type_id),
  depends_on_step_id bigint REFERENCES task_steps (task_step_id),
  status task_status_enum NOT NULL DEFAULT 'todo',
  due_at timestamptz(3),
  started_at timestamptz(3),
  completed_at timestamptz(3),
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

CREATE UNIQUE INDEX idx_task_steps_key ON task_steps (task_id, step_type_id, depends_on_step_id)
WHERE
  deleted_at IS NULL;

CREATE INDEX idx_task_steps_status ON task_steps (task_id, status);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE task_steps TO "task-manager";

CREATE TRIGGER task_steps BEFORE
UPDATE ON task_steps FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE task_assignments (
  task_assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (task_id),
  task_step_id bigint REFERENCES task_steps (task_step_id),
  assignee_type entity_type_enum NOT NULL,
  assignee_uuid uuid NOT NULL,
  assigned_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at timestamptz(3),
  completed_at timestamptz(3),
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz(3)
);

GRANT
SELECT
,
  INSERT,
UPDATE ON TABLE task_assignments TO "task-manager";

CREATE UNIQUE INDEX idx_task_assignments_assignee ON task_assignments (assignee_type, assignee_uuid, task_id, task_step_id)
WHERE
  deleted_at IS NULL;

CREATE TRIGGER task_assignments BEFORE
UPDATE ON task_assignments FOR EACH ROW
EXECUTE PROCEDURE set_updated_at ();

CREATE TABLE task_events (
  task_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (task_id),
  task_step_id bigint REFERENCES task_steps (task_step_id),
  event_type text NOT NULL,
  actor_type entity_type_enum,
  actor_uuid uuid,
  from_status task_status_enum,
  to_status task_status_enum,
  message text,
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_task_events_task ON task_events (task_id, created_at);

CREATE INDEX idx_task_events_step ON task_events (task_step_id, created_at);

CREATE INDEX idx_task_events_type ON task_events (event_type, created_at);

GRANT
SELECT
,
  INSERT ON TABLE task_events TO "task-manager";
