-- Boilerplate: create role if not exists
DO $do$
BEGIN IF EXISTS (
    SELECT
    FROM pg_catalog.pg_roles
    WHERE rolname = 'agent-manager'
  ) THEN RAISE NOTICE 'Role "agent-manager" already exists. Skipping.';

ELSE CREATE ROLE "agent-manager";

END IF;

END $do$;

-- Trigger function for auto-updating updated_at
CREATE
OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN NEW .updated_at = now();

RETURN NEW;

END;

$$ LANGUAGE plpgsql;

-- Enums
CREATE TYPE conversation_status_enum AS ENUM ('active', 'completed', 'cancelled', 'failed');

CREATE TYPE turn_status_enum AS ENUM (
  'pending',
  'streaming',
  'input-required',
  'complete',
  'failed'
);

CREATE TYPE message_role_enum AS ENUM ('user', 'assistant', 'system', 'tool-result');

-- Models: lookup table for LLM models (suitable for TableCache)
CREATE TABLE models (
  model_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  provider text NOT NULL,
  description text,
  context_window int,
  input_cost_per_million numeric(10, 4),
  output_cost_per_million numeric(10, 4),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz
);

CREATE TRIGGER models BEFORE
UPDATE ON models FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

GRANT SELECT,
INSERT,
UPDATE ON TABLE models TO "agent-manager";

-- Clients: lookup table for external callers (suitable for TableCache)
CREATE TABLE clients (
  client_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz
);

CREATE TRIGGER clients BEFORE
UPDATE ON clients FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

GRANT SELECT,
INSERT,
UPDATE ON TABLE clients TO "agent-manager";

-- Conversations: a thread of messages between a human and an agent
CREATE TABLE conversations (
  conversation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id text NOT NULL,
  status conversation_status_enum NOT NULL DEFAULT 'active',
  client_id int NOT NULL REFERENCES clients (client_id),
  client_version text NOT NULL,
  model_id int REFERENCES models (model_id),
  system_prompt text,
  starting_tools text[] NOT NULL DEFAULT ARRAY[]::text[],
  forked_from_conversation_id bigint REFERENCES conversations (conversation_id),
  forked_after_ordinal int,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX idx_conversations_by_uuid ON conversations (conversation_uuid);

CREATE INDEX idx_conversations_by_agent ON conversations (agent_id)
WHERE deleted_at IS NULL;

CREATE INDEX idx_conversations_by_status ON conversations (status)
WHERE deleted_at IS NULL;

CREATE INDEX idx_conversations_forked_from ON conversations (forked_from_conversation_id)
WHERE forked_from_conversation_id IS NOT NULL;

CREATE TRIGGER conversations BEFORE
UPDATE ON conversations FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- Turns: a request/response cycle within a conversation
-- Starts with a user message, ends when the assistant finishes (including any tool call loops)
CREATE TABLE turns (
  turn_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turn_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id bigint NOT NULL REFERENCES conversations (conversation_id),
  status turn_status_enum NOT NULL DEFAULT 'pending',
  client_id int NOT NULL REFERENCES clients (client_id),
  client_version text NOT NULL,
  model_id int REFERENCES models (model_id),
  added_tools text[] NOT NULL DEFAULT ARRAY[]::text[],
  removed_tools text[] NOT NULL DEFAULT ARRAY[]::text[],
  started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamptz,
  error text,
  finish_reason text,
  raw_finish_reason text,
  input_tokens int,
  output_tokens int,
  -- Timing: total wall-clock ms from first LLM call to final response
  total_latency_ms int,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX idx_turns_by_uuid ON turns (turn_uuid);

CREATE INDEX idx_turns_by_conversation ON turns (conversation_id, created_at);

CREATE INDEX idx_turns_by_status ON turns (conversation_id, status);

CREATE TRIGGER turns BEFORE
UPDATE ON turns FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- Messages: individual LLM-level messages, ordered by ordinal within a conversation
CREATE TABLE messages (
  message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id bigint NOT NULL REFERENCES conversations (conversation_id),
  turn_id bigint NOT NULL REFERENCES turns (turn_id),
  ordinal int NOT NULL,
  role message_role_enum NOT NULL,
  content jsonb NOT NULL DEFAULT '""'::jsonb,
  -- For assistant messages that invoke tools
  tool_calls jsonb,
  -- For tool-result messages: identifies which tool call this responds to
  tool_call_id text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  extra_data jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX idx_messages_by_uuid ON messages (message_uuid);

CREATE UNIQUE INDEX idx_messages_conversation_ordinal ON messages (conversation_id, ordinal);

CREATE INDEX idx_messages_by_turn ON messages (turn_id, ordinal);

CREATE INDEX idx_messages_by_role ON messages (conversation_id, role);

-- Grants
GRANT SELECT,
INSERT,
UPDATE ON TABLE conversations TO "agent-manager";

GRANT SELECT,
INSERT,
UPDATE ON TABLE turns TO "agent-manager";

GRANT SELECT,
INSERT ON TABLE messages TO "agent-manager";

GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "agent-manager";
