{{- if and .Values.database.gcpId (ne .Values.database.migrate false) }}
{{- $databaseInstance := default (printf "%s-pg-%s" .Values.gcp.env .Values.database.gcpId) .Values.database.instance -}}
{{- $passwordSecret := default dict .Values.database.passwordSecret -}}
{{- $secretName := default (printf "%s-db-credentials" .Values.database.gcpId) $passwordSecret.name -}}
{{- $secretKey := default "password" $passwordSecret.key -}}
{{- $user := default (printf "%s_pg-%s" .Values.gcp.env .Values.database.gcpId) .Values.database.user -}}
{{- $migrationJobName := printf "%s-migration-%s" (.Values.name | trunc 40 | trimSuffix "-") (now | date "200601021504") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $migrationJobName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "base-service.serviceAccountName" . }}
      initContainers:
        - name: cloudsql-proxy
          restartPolicy: Always
          args:
            - '--structured-logs'
            - '--private-ip'
            - '--address=0.0.0.0'
            - '{{ .Values.gcp.project }}:{{ default "us-central1" .Values.database.region }}:{{ $databaseInstance }}?port=5432'
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.2
          securityContext:
            runAsUser: 2 # non-root user
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          startupProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 2
            failureThreshold: 30
      containers:
        - name: {{ .Values.name }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.image.registry }}/{{ .Values.gcp.project }}/{{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.tag }}"
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.gcp.project | quote }}
            - name: NODE_ENV
              value: production
            - name: APP_ENV
              value: {{ ternary "staging" "production" (eq .Values.gcp.env "development") }}
            - name: PGHOST
              value: "127.0.0.1"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: {{ default .Values.name .Values.database.name | quote }}
            - name: PGUSER
              value: {{ $user | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName | quote }}
                  key: {{ $secretKey | quote }}
          command:
            - /nodejs/bin/node
            - /nodejs/app/node_modules/.bin/db-migrate
            - -e
            - {{ default "production" .Values.database.migrationEnvironment }}
            - --config
            - /nodejs/app/migrations/db-migrate.json
            - up
      restartPolicy: Never
{{- end -}}
