{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base-service.serviceAccountName" . }}
  labels:
    app: {{ .Values.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-service.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "base-service.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end -}}