{{- if .Values.temporal.workers -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-worker
  annotations:
    kubernetes.io/change-cause: {{ default "unknown" .Values.changeCause | quote }}
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 20
  selector:
    matchLabels:
      app: {{ .Values.name }}-worker
  replicas: {{ default 1 .Values.temporal.workers }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        team: {{ .Values.team }}
        app: {{ .Values.name }}-worker
        {{- if not ( index .Values "logging" "logz.io" ) }}
        no-logz-io: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ include "base-service.serviceAccountName" . }}
      containers:
        - name: {{ .Values.name }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.image.registry }}/{{ .Values.gcp.project }}/{{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.tag }}"
          resources:
            requests:
            {{- if default .Values.resources.cpu.requests .Values.temporal.resources.cpu.requests }}
              cpu: {{ default .Values.resources.cpu.requests .Values.temporal.resources.cpu.requests }}
            {{- end -}}
            {{- if default .Values.resources.memory.requests .Values.temporal.resources.memory.requests }}
              memory: {{ default .Values.resources.memory.requests .Values.temporal.resources.memory.requests }}
            {{- end }}
            limits:
            {{- if default .Values.resources.cpu.limits .Values.temporal.resources.cpu.limits }}
              cpu: {{ default .Values.resources.cpu.limits .Values.temporal.resources.cpu.limits }}
            {{- end -}}
            {{- if default .Values.resources.memory.limits .Values.temporal.resources.memory.limits }}
              memory: {{ default .Values.resources.memory.limits .Values.temporal.resources.memory.limits }}
            {{- end }}
          env:
            - name: GCP_REGION
              value: {{ .Values.gcp.region | default "us-central1" }}
            - name: NODE_ENV
              value: production
            - name: APP_ENV
              value: {{ ternary "staging" "production" (eq .Values.gcp.env "development") }}
            - name: TEMPORAL_WORKER
              value: "true"
            {{- if .Values.database.gcpId }}
            - name: DATABASE_ID
              value: "{{ .Values.gcp.project }}:{{ default "us-central1" .Values.database.region }}:pg-{{- ternary "dev-" "" (eq .Values.gcp.env "development") -}}{{ .Values.database.gcpId }}"
            {{- end }}
            {{- include "base-service.env" . | trimSuffix "\n" | indent 12 }}
            {{- include "base-service.worker-env" . | trimSuffix "\n" | indent 12 }}
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /health
              port: 3000
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /health
              port: 3000
          {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- range .Values.volumeMounts }}
          - {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- if .Values.sidecars }}
        {{- range .Values.sidecars }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 10 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.name }}-worker
              topologyKey: kubernetes.io/hostname
{{- end -}}
