BEGIN;

CREATE FUNCTION set_credit_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION set_credit_updated_at() FROM PUBLIC;

-- An optional scope is an external identity, e.g. the provider whose minutes may
-- be redeemed. NULL is unscoped; it must not permit duplicate currency accounts.
CREATE TABLE credit_accounts (
    credit_account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    individual_uuid uuid NOT NULL,
    currency text NOT NULL CHECK (currency <> '' AND currency = upper(btrim(currency))),
    scope_uuid uuid,
    balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0 AND balance < 'Infinity'::numeric),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamptz CHECK (deleted_at IS NULL),
    extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE NULLS NOT DISTINCT (individual_uuid, currency, scope_uuid)
);
CREATE TRIGGER credit_accounts BEFORE UPDATE ON credit_accounts
    FOR EACH ROW EXECUTE FUNCTION set_credit_updated_at();

CREATE TYPE credit_entry_status_enum AS ENUM ('reserved', 'posted', 'voided');
CREATE TABLE credit_entries (
    credit_entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_entry_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    credit_account_id bigint NOT NULL REFERENCES credit_accounts (credit_account_id),
    idempotency_key text NOT NULL UNIQUE CHECK (btrim(idempotency_key) <> ''),
    -- Positive grants credit; negative spends it. No rounding or floating point.
    amount numeric NOT NULL CHECK (
        amount <> 0 AND amount > '-Infinity'::numeric AND amount < 'Infinity'::numeric
    ),
    status credit_entry_status_enum NOT NULL DEFAULT 'posted',
    event_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamptz CHECK (deleted_at IS NULL),
    extra_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (status = 'posted' OR amount < 0)
);
CREATE UNIQUE INDEX idx_credit_entries_by_uuid ON credit_entries (credit_entry_uuid);
CREATE INDEX idx_credit_entries_account_history ON credit_entries (credit_account_id, credit_entry_id);
CREATE TRIGGER credit_entries BEFORE UPDATE ON credit_entries
    FOR EACH ROW EXECUTE FUNCTION set_credit_updated_at();

-- This is the only runtime path that changes cached balances. An AFTER trigger
-- is essential: INSERT ... ON CONFLICT DO NOTHING must not change a balance.
-- Pin name resolution and keep execution private; callers cannot write balances.
CREATE FUNCTION apply_credit_entry() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
    balance_delta numeric;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status = 'voided' THEN
            RAISE EXCEPTION 'A credit entry cannot be created voided' USING ERRCODE = '23514';
        END IF;
        balance_delta := NEW.amount;
    ELSE
        IF (to_jsonb(NEW) - ARRAY['status', 'updated_at']) IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['status', 'updated_at']) THEN
            RAISE EXCEPTION 'Credit entry details are immutable' USING ERRCODE = '23514';
        END IF;
        IF NEW.status = OLD.status THEN
            RETURN NULL; -- Repeating a transition has no balance effect.
        END IF;
        IF OLD.status <> 'reserved' OR NEW.status NOT IN ('posted', 'voided') THEN
            RAISE EXCEPTION 'Only reserved credit debits can be posted or voided' USING ERRCODE = '23514';
        END IF;
        balance_delta := CASE WHEN NEW.status = 'voided' THEN -NEW.amount ELSE 0 END;
    END IF;

    IF balance_delta <> 0 THEN
        -- UPDATE locks the account until commit and evaluates against the latest
        -- balance. Its CHECK constraint rejects overdrafts, including concurrent
        -- spends; failure rolls back both the entry and balance change.
        UPDATE credit_accounts SET balance = balance + balance_delta
        WHERE credit_account_id = NEW.credit_account_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Credit account does not exist' USING ERRCODE = '23503';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION apply_credit_entry() FROM PUBLIC;
CREATE TRIGGER credit_entries_apply AFTER INSERT OR UPDATE ON credit_entries
    FOR EACH ROW EXECUTE FUNCTION apply_credit_entry();

-- Operator-only repair. Lock before taking the sum so committed writes that we
-- waited for are included, and later writes apply their deltas after our repair.
-- NO KEY UPDATE is compatible with the entry foreign key's KEY SHARE lock.
CREATE FUNCTION recompute_balance(p_credit_account_id bigint) RETURNS numeric
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE
    recomputed_balance numeric;
BEGIN
    PERFORM 1 FROM credit_accounts
    WHERE credit_account_id = p_credit_account_id FOR NO KEY UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Credit account does not exist: %', p_credit_account_id
            USING ERRCODE = '23503';
    END IF;

    SELECT COALESCE(SUM(amount), 0) INTO recomputed_balance
    FROM credit_entries
    WHERE credit_account_id = p_credit_account_id AND status <> 'voided';

    -- Keep the nonnegative constraint: invalid history must fail, not be clamped.
    UPDATE credit_accounts SET balance = recomputed_balance
    WHERE credit_account_id = p_credit_account_id;
    RETURN recomputed_balance;
END;
$$;
REVOKE ALL ON FUNCTION recompute_balance(bigint) FROM PUBLIC;
COMMENT ON FUNCTION recompute_balance(bigint) IS 'Operator-only: lock a credit account, recompute its available balance from non-voided entries, repair the cache and return the balance.';

-- Standard deletion columns are intentionally constrained to NULL: neither soft
-- nor hard deletion is a ledger operation. Correct posted entries by appending.
GRANT SELECT ON credit_accounts, credit_entries TO "payment-manager";
GRANT INSERT (individual_uuid, currency, scope_uuid, extra_data)
    ON credit_accounts TO "payment-manager";
GRANT INSERT (credit_account_id, idempotency_key, amount, status, event_at, extra_data)
    ON credit_entries TO "payment-manager";
GRANT UPDATE (status) ON credit_entries TO "payment-manager";
GRANT USAGE ON SEQUENCE credit_accounts_credit_account_id_seq,
    credit_entries_credit_entry_id_seq TO "payment-manager";

COMMENT ON TABLE credit_accounts IS 'Available credit per individual, currency and optional external scope; includes reserved debits.';
COMMENT ON COLUMN credit_accounts.scope_uuid IS 'Optional external redemption scope, e.g. a provider UUID. NULL means unscoped.';
COMMENT ON COLUMN credit_accounts.balance IS 'SUM(amount) of all non-voided entries, maintained atomically by the entry trigger.';
COMMENT ON TABLE credit_entries IS 'Signed credit ledger; only reserved negative entries may transition to posted or voided.';
COMMENT ON COLUMN credit_entries.idempotency_key IS 'Globally unique operation key, retained after voiding. Conflicting retries must compare the original payload.';

COMMIT;
